CREATE TABLE IF NOT EXISTS restaurants (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    address text NOT NULL CHECK (address <> '')
);

CREATE TABLE IF NOT EXISTS clients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    address text NOT NULL CHECK (address <> '')
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id INTEGER REFERENCES restaurants(id),
    client_id INTEGER REFERENCES clients(id),
    courier_id INTEGER REFERENCES couriers(id),
    menu_id INTEGER REFERENCES menus(id),
    order_time TIME NOT NULL,
    delivery_time TIME
);

CREATE TABLE IF NOT EXISTS couriers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    total_orders INTEGER
);

CREATE TABLE IF NOT EXISTS menus (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    price money NOT NULL CHECK (price <> '')
);


INSERT INTO restaurants(name, address)
    VALUES ('Dominos', ' street, 52');

INSERT INTO restaurants(name, address)
    VALUES ('Pizza Hut', 'ziqwjrfaosi st., ap. 213');

INSERT INTO restaurants(name, address)
    VALUES ('Pizza cat', 'zxcqer, 102');

INSERT INTO restaurants(name, address)
    VALUES ('Tasty pizza', 'aqwrasfxzc, 24125');

INSERT INTO couriers(name, total_orders)
    VALUES ('Ivan', 0);

INSERT INTO couriers(name, total_orders)
    VALUES ('Petro', 0);

INSERT INTO couriers(name, total_orders)
    VALUES ('Misha', 0);

INSERT INTO menus(name, price)
    VALUES ('Pizza pepperoni', 120.55);

INSERT INTO menus(name, price)
    VALUES ('Pizza with pineapples', 140.20);

INSERT INTO menus(name, price)
    VALUES ('Pizza with olives', 150);

INSERT INTO menus(name, price)
    VALUES ('Pizza mammamia', 100.99);

INSERT INTO clients(name, address)
    VALUES ('Oleg', 'Bulkina st. ap.124');

INSERT INTO clients(name, address)
    VALUES ('Ihor', 'Pecherska st. ap.151');


