CREATE TABLE IF NOT EXISTS restaurants (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    address text NOT NULL CHECK (address <> '')
);

CREATE TABLE IF NOT EXISTS clients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    address text NOT NULL CHECK (address <> '')
);

CREATE TABLE IF NOT EXISTS couriers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    delivery_service text NOT NULL (delivery_service <> ''),
);

CREATE TABLE IF NOT EXISTS menus (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    price money NOT NULL CHECK (price <> '')
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id INTEGER REFERENCES restaurants(id) on delete cascade on update cascade,
    client_id INTEGER REFERENCES clients(id) on delete cascade on update cascade,
    courier_id INTEGER REFERENCES couriers(id) on delete cascade on update cascade,
    menu_id INTEGER REFERENCES menus(id) on delete cascade on update cascade,
    order_time TIME NOT NULL,
    delivery_time TIME
);


INSERT INTO restaurants(name, address)
    VALUES
    ('Dominos', ' street, 52'),
    ('Pizza Hut', 'ziqwjrfaosi st., ap. 213'),
    ('Pizza cat', 'zxcqer, 102'),
    ('Tasty pizza', 'aqwrasfxzc, 24125');


INSERT INTO couriers(name, delivery_service)
    VALUES
    ('Ivan', 'Uber Eats'),
    ('Petro', 'Glovo'),
    ('Misha', 'Raketa');


INSERT INTO menus(name, price)
    VALUES
    ('Pizza pepperoni', 120.55),
    ('Pizza with pineapples', 140.20),
    ('Pizza with olives', 150),
    ('Pizza mammamia', 100.99);

INSERT INTO clients(name, address)
    VALUES
    ('Oleg', 'Bulkina st. ap.124'),
    ('Ihor', 'Pecherska st. ap.151');

INSERT INTO orders(restaurant_id, client_id, courier_id, menu_id, order_time, delivery_time)
    VALUES
    ('1', '2', '1', '2', '13:00:00', '13:50:20'),
    ('2', '2', '1', '1', '15:50:13', '16:20:01'),
    ('2', '2', '1', '3', '18:50:14', '19:20:12'),
    ('2', '2', '1', '4', '10:12:53', '11:00:00'),
    ('2', '1', '1', '1', '14:10:43', '14:30:05'),
    ('3', '1', '2', '1', '11:20:15', '12:00:21'),
    ('2', '1', '2', '2', '21:00:51', '21:40:16'),
    ('1', '2', '3', '1', '20:30:41', '21:05:17'),
    ('2', '1', '3', '3', '13:50:13', '14:20:01'),
    ('1', '2', '3', '1', '16:20:42', '16:50:21');


